# Generated by Django 5.0.3 on 2024-03-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number',
        ),
    ]
