# Generated by Django 4.2.2 on 2024-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_name_az_project_name_en_project_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
