# Generated by Django 4.2.3 on 2024-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateField(auto_now_add=True, default='2024-04-24', verbose_name='Göndərilmə Tarixi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Baxdım'),
        ),
    ]
