# Generated by Django 5.0.3 on 2024-03-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('swiper_slide_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swiper_slide_count', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='SlideContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_contents', to='home.slider')),
            ],
        ),
    ]
