# Generated by Django 5.0.3 on 2024-03-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_statistics_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='swiper_slide_count',
        ),
        migrations.RemoveField(
            model_name='videoslider',
            name='swiper_slide_count',
        ),
    ]
