# Generated by Django 5.0.3 on 2024-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider_title_alter_slider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
