# Generated by Django 5.0.3 on 2024-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
