# Generated by Django 4.2.2 on 2024-03-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_employee_fullname_az_employee_fullname_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fullname_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fullname_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fullname_ru',
        ),
    ]
