# Generated by Django 4.2.2 on 2024-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_employee_fullname_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
